# Generated by Django 5.2.4 on 2026-01-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_created_at_project_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('objective', models.TextField()),
                ('profession', models.CharField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
    ]
