# Generated by Django 5.2.4 on 2026-01-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_skill_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text="Font Awesome class, e.g., 'fab fa-python'", max_length=100),
        ),
    ]
