# Generated by Django 5.2.4 on 2026-01-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_skill_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='Your Fname', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='your Lname', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='mname',
            field=models.CharField(default='Your Mname', max_length=50),
        ),
    ]
