# Generated by Django 5.2.4 on 2026-01-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_profile_name_profile_fname_profile_lname_and_more'),
    ]

    operations = [
        migrations.RenameField(
    model_name='experience',
    old_name='compony',
    new_name='company',
),

    ]
