# Generated by Django 5.2.4 on 2026-01-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_certification_chatlog_education_otherlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='credential_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
