# Generated by Django 5.2.4 on 2026-01-13 09:37

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_certification_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate',
            field=models.FileField(upload_to='certificates/', validators=[main.models.validate_certificate_file]),
        ),
    ]
