# Generated by Django 5.2.4 on 2026-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_certification_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/thumbnails/'),
        ),
    ]
