# Generated by Django 5.2.4 on 2026-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_certification_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='year',
            field=models.DateField(max_length=50),
        ),
    ]
